spring.application.name=book-catalog-web


# ----------- configurasi datasource (CP / connection pool)
spring.datasource.hikari.connection-timeout=30000

# berapa lama boleh tidak terkoneksi
spring.datasource.hikari.idle-timeout=600000

# menentukan waktu max obj connection ada di pool, mencegah memutus koneksi secara tiba-tiba
spring.datasource.hikari.max-lifetime=1800000

# menentukan jumlah obj connection dalam pool
spring.datasource.hikari.maximum-pool-size=10


# ---------- [Configurasi untuk koneksi ke db]----------------
spring.datasource.url=jdbc:postgresql://localhost:5432/book_catalog
spring.datasource.username=postgres
spring.datasource.password=postgres

# ---------- [Configurasi untuk jpa]----------------
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true